language: ruby
env:
  - DB=mysql
  - DB=postgres
  - DB=sqlite
services:
  - mysql
  - postgresql
rvm:
  - "1.8.7"
  - "1.9.3"
  - "2.0.0"
  - "2.1"
before_script:
  - cp config/database.yml.travis config/database.yml
  - 'echo "test: *${DB}" >> config/database.yml'
  - bundle exec rake db:create
  - bundle exec rake db:schema:load
  - bundle exec rake db:migrate
script:
  - bundle exec rake spec
# Temporary workaround for broken Rubygems on Travis
before_install:
  - gem update --system 2.1.11
  - gem --version
